title: Meu aprendizado em linguagem C
description: >-
  Aqui será documentado minha evolução na linguagem C. Exercícios, comentários,
  Listas de exercícios de SI do Dom Bosco, e outras listas também. Além de tudo
  o tipo de material que eu for encontrando ao longo do caminho.
template:
  repo: meu-aprendizado-em-linguagem-c-template
  name: meu-aprendizado-em-linguagem-c
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
